FROM node:4.4.3

# We create an unprivileged user, prosaically called app,
# to run the app inside the container. If you don’t do this,
# then the process inside the container will run as root,
# which is against security best practices and principles.
RUN useradd --user-group --create-home --shell /bin/false app &&\
  npm install --global npm@3.8.7

# Home env variable
ENV HOME=/home/app

# Copy package.json and npm-shrinkwrap.json to
# tmp and install dependencies
WORKDIR /tmp
COPY package.json npm-shrinkwrap.json /tmp/
RUN npm config set registry http://registry.npmjs.org/ && \
    npm install && npm shrinkwrap

# Copy node_modules into the /home/app/chat/
COPY node_modules $HOME/chat

# Change onwer to app with reading priveleges.
RUN chown -R app:app $HOME/*

# set user
USER app

# Set working directory to /home/app/chat
WORKDIR $HOME/chat

# run command
CMD ["node", "index.js"]

